spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.107.204:3306/wechat?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  #jpa配置
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
  #RabbitMQ配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #virtual-host: /
    exchangename: direct-exchange-faz
    delayexchangename: direct-delayexchange-faz
    queuename: direct-queue-faz
    delayqueuename: direct-delayqueue-faz
    routingkey: direct-routingkey-faz
    delayroutingkey: direct-delayroutingkey-faz
  redis:
    host: 101.132.107.204
    port: 6379
    #password: requirepass
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.fanaozhe.springbootdemo.entity
  configuration:
    map-underscore-to-camel-case: true

#阿里云短信配置
templateCode: SMS_197610357
#templateCode: SMS_199198112
signName: 杭城流浪者
accessKeyId: LTAI4FyjHiwGgK6UyYX3jp2T
secret: bCKGM6thpmnjuQg9AYtK1aWu1w7wHm

